### ISSUE TITLE
Crashes when loading Smash Ultimate (Ver. 10.1.0)

### ISSUE THREAD

**Issue by GANP0N** [jam1garner/smush-discord#6]
I meet with the "An error occurred" screen shortly after the "Nintendo Switch" splash when booting smash ultimate.
Could be that this was made for an older version of smash (from back in june) and perhaps outdated offsets for current version (Ver. 10.1.0).

Using latest version of smush-discord (v0.1.0)
Atmosphère 0.16.2

**Comment by jam1garner** [comment]
Oh yeah I forgot I need to add offset searching for this
